include(${CMAKE_CURRENT_LIST_DIR}/backpressure_test/backpressure_test.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/i2s_master_external_clock_test/i2s_master_external_clock_test.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/i2s_master_test/i2s_master_test.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/i2s_slave_test/i2s_slave_test.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/tdm_slave_tx16_cb_test/i2s_tdm_tx16_slave_test.cmake)
